<a href="https://colab.research.google.com/github/okdohyuk-hello-world/learn-py/blob/main/basic/%5BRecap%5D_Numpy___Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<br>

## 1. Numpy Recap

In [1]:
import numpy as np

<br>

#### np.ndarray 만들기

In [2]:
v1 = np.array([1, 2, 3, 4]) # 배열(Array)
v1

array([1, 2, 3, 4])

In [3]:
type(v1) # 어떤 자료형일까요? N - Dimensional array

numpy.ndarray

In [4]:
v1.dtype # d(ata)-type

dtype('int64')

In [5]:
v2 = np.array([1, 2, 4.3, 10])
v2.dtype

dtype('float64')

In [8]:
v3 = np.array([1, 2, 3, '안녕하세요'])
v3

array(['1', '2', '3', '안녕하세요'], dtype='<U21')

In [7]:
v1.shape # '모양'을 영어로?

(4,)

In [12]:
sample_matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
sample_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
sample_matrix.shape

(3, 3)

In [18]:
sample_matrix[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [19]:
sample_matrix[:,2]

array([3, 6, 9])

In [ ]:
v1 = np.array([[1, 2, 3], [4, 5, 6]]) # 진짜 행렬 만들기
v1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
v1.shape

(2, 3)

<br>

#### np.arange & np.reshape

In [ ]:
v1 = np.?(5) # 'a'rray of 'range'
v1

array([0, 1, 2, 3, 4])

In [ ]:
v2 = np.arange(1, 10, 2)
v2

array([1, 3, 5, 7, 9])

In [ ]:
v4 = np.arange(1, 10, 2) ? 2 # 제곱 연산자가 무엇이었죠?
v4

array([ 1,  9, 25, 49, 81], dtype=int32)

In [ ]:
v1 = np.arange(12)
v1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
v2 = v1.?(2, 6) # '모양'을 '다시' 고치다
v2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
v3 = v1.reshape(2, 6, order='F') # C & Fortran
v3

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

In [ ]:
v1 = np.arange(12).reshape(2, 6)
v1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

<br>

#### np.ndarray 의 사칙연산

In [ ]:
v1 = np.arange(1, 5).reshape(2, 2)
v1

array([[1, 2],
       [3, 4]])

In [ ]:
np.max(v1)

4

In [ ]:
np.min(v1)

1

In [ ]:
np.mean(v1)

2.5

In [ ]:
np.std(v1)

1.118033988749895

<br>

#### 행렬 간의 사칙연산

In [ ]:
v1

array([[1, 2],
       [3, 4]])

In [ ]:
np.?(v1, v1) # 더하기

array([[2, 4],
       [6, 8]])

In [ ]:
np.?(v1, v1) # 빼기

array([[0, 0],
       [0, 0]])

In [ ]:
np.?(v1, v1) # 곱하기 (element-wise multiply)

array([[ 1,  4],
       [ 9, 16]])

In [ ]:
np.?(v1, v1) # 행렬곱 (dot-product)

array([[ 7, 10],
       [15, 22]])

<br>

## 2. Pandas Recap

In [ ]:
import pandas as pd

<br>

#### Series

In [ ]:
a = ?([1, 3, 5, 7])
a

0    1
1    3
2    5
3    7
dtype: int64

In [ ]:
a.values

array([1, 3, 5, 7], dtype=int64)

In [ ]:
a.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
a2 = pd.Series([1, 3, 5, 7], index=['a', 'b', 'c', 'd'])
a2

a    1
b    3
c    5
d    7
dtype: int64

<br>

#### DataFrame

In [ ]:
df = pd.read_excel('cosmetics_.xlsx')
df.head()

gender  marriage  edu  job  mincome  aware  count  amount  decision  \
0       1         1    4    1        2      2      1   11000         2   
1       2         1    4    9        2      1      4   30000         1   
2       2         2    4    4        3      1      6  100000         3   
3       2         2    4    7        5      2      6   65000         3   
4       1         2    6    6        5      2      2   50000         2   

   propensity  skin  promo  location  satisf_b  satisf_i  satisf_al  \
0           1     1      1         2         5         2          2   
1           1     3      2         3         2         3          3   
2           2     3      2         2         4         5          4   
3           2     5      2         3         3         4          4   
4           2     3      2         3         3         3          3   

   repurchase  
0           2  
1           4  
2           4  
3           4  
4           3

![image.png](attachment:image.png)

In [ ]:
df['amount'] # 평균 1회 구매 비용

In [ ]:
df.amount

In [ ]:
# # DataFrame에서 하나의 Cell에 해당하는 값을 얻어내는 4가지 방법

# df['amount'][0] # 열에 접근 후 Series의 index로 접근
# df.loc[0]['amount'] # 행에 접근 후 Series의 index로 접근
# df.loc[0, 'amount'] # 행 이름과 열 이름을 지정하여 접근 (loc 활용)
# df.at[0, 'amount'] # 행 이름과 열 이름을 지정하여 접근 (at 활용)
# df.iloc[0, 7] # indexed-location 기반으로 index number 기준 행 & 열 지정하여 접근 

In [ ]:
df.?[3, 'amount'] # located "at" 3 & 'amount'

65000

In [ ]:
df.loc[3, 'amount']

65000

In [ ]:
df['total_payment'] = df['amount'] * df['count'] # 평균 1회 구매 비용 / 구매 횟수 == 총 연 구매 금액
df.head()

gender  marriage  edu  job  mincome  aware  count  amount  decision  \
0       1         1    4    1        2      2      1   11000         2   
1       2         1    4    9        2      1      4   30000         1   
2       2         2    4    4        3      1      6  100000         3   
3       2         2    4    7        5      2      6   65000         3   
4       1         2    6    6        5      2      2   50000         2   

   propensity  skin  promo  location  satisf_b  satisf_i  satisf_al  \
0           1     1      1         2         5         2          2   
1           1     3      2         3         2         3          3   
2           2     3      2         2         4         5          4   
3           2     5      2         3         3         4          4   
4           2     3      2         3         3         3          3   

   repurchase  total_payment  
0           2          11000  
1           4         120000  
2           4         600000  
3           4         390000  
4           3         100000

In [ ]:
df.?(8, 'total_payment_', df['amount'] * df['count']) # index 기준으로 8번 열에 새로운 열을 "삽입"
df.head()

gender  marriage  edu  job  mincome  aware  count  amount  total_payment_  \
0       1         1    4    1        2      2      1   11000           11000   
1       2         1    4    9        2      1      4   30000          120000   
2       2         2    4    4        3      1      6  100000          600000   
3       2         2    4    7        5      2      6   65000          390000   
4       1         2    6    6        5      2      2   50000          100000   

   decision  propensity  skin  promo  location  satisf_b  satisf_i  satisf_al  \
0         2           1     1      1         2         5         2          2   
1         1           1     3      2         3         2         3          3   
2         3           2     3      2         2         4         5          4   
3         3           2     5      2         3         3         4          4   
4         2           2     3      2         3         3         3          3   

   repurchase  total_payment  
0           2          11000  
1           4         120000  
2           4         600000  
3           4         390000  
4           3         100000

In [ ]:
del df['total_payment']
del df['total_payment_']

In [ ]:
df_gender = df[df['gender'] == 1] 
df_gender.head()

gender  marriage  edu  job  mincome  aware  count  amount  decision  \
0        1         1    4    1        2      2      1   11000         2   
4        1         2    6    6        5      2      2   50000         2   
7        1         1    6    4        5      4     10   39000         3   
11       1         1    2    5        3      2      1   30000         3   
14       1         2    4    4        6      2      2   60000         3   

    propensity  skin  promo  location  satisf_b  satisf_i  satisf_al  \
0            1     1      1         2         5         2          2   
4            2     3      2         3         3         3          3   
7            2     2      1         2         4         4          4   
11           2     3      2         2         3         3          3   
14           2     1      2         5         3         3          3   

    repurchase  
0            2  
4            3  
7            4  
11           3  
14           4

In [ ]:
df_reacount = df[ df['count'] < 10 & df['count'] >= 1 ] # 연 구매 횟수 1회 ~ 9회 이하 & 각 조건식을 ()로 감싸줘야 합니다.
df_reacount.head()

gender  marriage  edu  job  mincome  aware  count  amount  decision  \
0       1         1    4    1        2      2      1   11000         2   
1       2         1    4    9        2      1      4   30000         1   
2       2         2    4    4        3      1      6  100000         3   
3       2         2    4    7        5      2      6   65000         3   
4       1         2    6    6        5      2      2   50000         2   

   propensity  skin  promo  location  satisf_b  satisf_i  satisf_al  \
0           1     1      1         2         5         2          2   
1           1     3      2         3         2         3          3   
2           2     3      2         2         4         5          4   
3           2     5      2         3         3         4          4   
4           2     3      2         3         3         3          3   

   repurchase  
0           2  
1           4  
2           4  
3           4  
4           3

In [ ]:
df['edu'].value_counts()

4    136
2     30
6     29
8     26
7     15
3      9
5      2
Name: edu, dtype: int64

In [ ]:
df['edu'].value_counts(sort=False)

2     30
3      9
4    136
5      2
6     29
7     15
8     26
Name: edu, dtype: int64

In [ ]:
def num_to_character(data):
    if data == 1:
        return 'male'
    else:
        return 'female'

In [ ]:
df['gender_2'] = df['gender'].?(num_to_character) # 적용하다
df.head()

gender  marriage  edu  job  mincome  aware  count  amount  decision  \
0       1         1    4    1        2      2      1   11000         2   
1       2         1    4    9        2      1      4   30000         1   
2       2         2    4    4        3      1      6  100000         3   
3       2         2    4    7        5      2      6   65000         3   
4       1         2    6    6        5      2      2   50000         2   

   propensity  skin  promo  location  satisf_b  satisf_i  satisf_al  \
0           1     1      1         2         5         2          2   
1           1     3      2         3         2         3          3   
2           2     3      2         2         4         5          4   
3           2     5      2         3         3         4          4   
4           2     3      2         3         3         3          3   

   repurchase gender_2  
0           2     male  
1           4   female  
2           4   female  
3           4   female  
4           3     male